CREATE TABLE users (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL, 
  password VARCHAR(255) NOT NULL,
  cpf CHAR(11) NOT NULL, 
  birthdate DATE NOT NULL, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  pin_code VARCHAR(6),
  address_id INTEGER NOT NULL,
  CONSTRAINT users_address_id_fk FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE CASCADE ON UPDATE CASCADE
)