CREATE TABLE events (
  id SERIAL NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  details VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  maximum_attendees INTEGER NOT NULL,
  owner_id SERIAL NOT NULL,
  CONSTRAINT events_owner_id_fk FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);